# -*- coding: utf-8 -*-
"""appBencana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvBbrq_ottjspV80OzvTTS2IpTQ6o2yQ
"""

import streamlit as st
import pandas as pd
import altair as alt

# Konfigurasi Halaman
st.set_page_config(page_title="Dashboard Kehutanan & Bencana Indonesia", layout="wide")

# Fungsi untuk membersihkan angka format Indonesia (titik ribuan, koma desimal)
def clean_id_number(series):
    return pd.to_numeric(series.astype(str).str.replace('.', '', regex=False).str.replace(',', '.'), errors='coerce')

# 1. Load Data
@st.cache_data
def load_data():
    # Tree Cover Loss
    df_loss = pd.read_excel('treecoverloss2001-2024.xlsx')

    # Deforestasi (Cleaning numeric columns)
    df_def = pd.read_excel('deforestasi2024.xlsx')
    for col in ['HK', 'HL', 'HPT', 'HP', 'HPK', 'APL']:
        df_def[col] = clean_id_number(df_def[col])

    # Kasus Kehutanan
    df_kasus = pd.read_excel('kasushutan_2024.xlsx')
    df_kasus.columns = df_kasus.columns.str.strip()
    df_kasus['JUMLAH'] = clean_id_number(df_kasus['JUMLAH'])
    # Ensure all numeric columns are properly typed
    for col in df_kasus.columns:
        if col != 'PROVINSI' and col not in ['ILLEGAL_LOGGING', 'PERAMBAHAN_HUTAN', 'TUMBUHAN_SATWA_LIAR']:
            df_kasus[col] = pd.to_numeric(df_kasus[col], errors='coerce')

    # Data Bencana
    df_bencana = pd.read_excel('Dataset_Bencana_Nasional_Lengkap.xlsx')

    return df_loss, df_def, df_kasus, df_bencana

df_loss, df_def, df_kasus, df_bencana = load_data()

# --- HEADER ---
st.title("🌲 Analisis Kondisi Hutan dan Dampak Lingkungan")
st.markdown("""
Bagaimana kondisi hutan kita?
""")

# --- tren kehilangan tutupan pohon ---
st.header("Tren Kehilangan Tutupan Pohon (2001-2024)")
col1, col2 = st.columns([3, 1])

with col1:
    line_chart = alt.Chart(df_loss).mark_line(point=True, color='#e63946').encode(
        x=alt.X('year:O', title='Tahun'),
        y=alt.Y('loss_ha:Q', title='Luas Kehilangan (Ha)'),
        tooltip=['year', 'loss_ha']
    ).interactive()
    st.altair_chart(line_chart, use_container_width=True)

with col2:
    st.write("**Narasi:**")
    total_loss = df_loss['loss_ha'].sum()
    st.info(f"Total kehilangan tutupan pohon sejak 2001 mencapai **{total_loss:,.0f} Ha**.")
    st.write("Fluktuasi angka tahunan menunjukkan dinamika perubahan penggunaan lahan dan efektivitas kebijakan proteksi hutan.")

# --- deforestasi hutan berdasarkan fungsi ---
st.header("Deforestasi Hutan Berdasarkan Fungsi")
provinsi_select = st.selectbox("Pilih Provinsi:", df_def['PROVINSI'].unique())

df_def_filtered = df_def[df_def['PROVINSI'] == provinsi_select].melt(
    id_vars='PROVINSI', value_vars=['HK', 'HL', 'HPT', 'HP', 'HPK', 'APL'],
    var_name='Fungsi Hutan', value_name='Luas (Ha)'
)

# Radial/Polar bar chart untuk variasi
radial_chart = alt.Chart(df_def_filtered).mark_arc(innerRadius=50, outerRadius=120).encode(
    theta=alt.Theta('Luas (Ha):Q', stack=True),
    color=alt.Color('Fungsi Hutan:N', scale=alt.Scale(scheme='viridis'), legend=alt.Legend(title='Fungsi Hutan')),
    tooltip=['Fungsi Hutan', alt.Tooltip('Luas (Ha):Q', format=',.0f')]
).properties(height=350)
st.altair_chart(radial_chart, use_container_width=True)

st.caption("HK: Hutan Konservasi, HL: Hutan Lindung, HP: Hutan Produksi, APL: Area Penggunaan Lain.")

# --- kriminalitas kehutanan ---
st.header("Pelanggaran Hukum Kehutanan 2024")
top_kasus = df_kasus.sort_values('JUMLAH', ascending=False).head(10)

# Circle/bubble chart untuk visualisasi yang berbeda
kasus_chart = alt.Chart(top_kasus).mark_circle(size=200).encode(
    x=alt.X('JUMLAH:Q', title='Jumlah Kasus', scale=alt.Scale(zero=False)),
    y=alt.Y('PROVINSI:N', sort='-x', title='Provinsi'),
    size=alt.Size('JUMLAH:Q', legend=None, scale=alt.Scale(range=[100, 2000])),
    color=alt.Color('JUMLAH:Q', scale=alt.Scale(scheme='redyellowgreen', reverse=True), legend=None),
    tooltip=[alt.Tooltip('PROVINSI:N'),
             alt.Tooltip('JUMLAH:Q', format=','),
             alt.Tooltip('ILLEGAL_LOGGING:N', format=''),
             alt.Tooltip('PERAMBAHAN_HUTAN:N', format=''),
             alt.Tooltip('TUMBUHAN_SATWA_LIAR:N', format='')]
)
st.altair_chart(kasus_chart, use_container_width=True)
st.write("> **Catatan:** Grafik di atas menunjukkan 10 provinsi dengan jumlah kasus tertinggi. Hover (arahkan kursor) pada batang grafik untuk melihat detail jenis pelanggaran.")

# --- BAGIAN 4: HUBUNGAN DENGAN BENCANA ---
st.header("Rekapitulasi Kejadian Bencana 2025")

# Initialize session state untuk show_all
if 'show_all_provinces' not in st.session_state:
    st.session_state.show_all_provinces = False

# Tombol untuk menampilkan semua provinsi
col_btn, col_filter = st.columns([1, 3])

with col_btn:
    if st.button("📍 Tampilkan Semua", help="Klik untuk menampilkan semua provinsi"):
        st.session_state.show_all_provinces = not st.session_state.show_all_provinces

with col_filter:
    if st.session_state.show_all_provinces:
        provinsi_selected = sorted(df_bencana['Provinsi'].unique())
        st.info("✅ Menampilkan semua provinsi")
    else:
        provinsi_selected = st.multiselect(
            "Filter Provinsi:",
            options=sorted(df_bencana['Provinsi'].unique()),
            default=sorted(df_bencana['Provinsi'].unique())[:5],  # Default 5 provinsi pertama
            key='rekapitulasi_provinsi'
        )

# Jenis bencana yang ditampilkan: Banjir
bencana_selected = ['Banjir']

# Prepare data with melt
if provinsi_selected:
    df_filtered = df_bencana[df_bencana['Provinsi'].isin(provinsi_selected)]
    
    # Melt data - hanya untuk Banjir
    prepared_df = pd.melt(df_filtered,
                          id_vars=['Provinsi'],
                          value_vars=bencana_selected,
                          var_name='Kategori_Bencana',
                          value_name='Jumlah_Kejadian')
    
    # Filter hanya data > 0
    prepared_df = prepared_df[prepared_df['Jumlah_Kejadian'] > 0]
    
    # Groupby dan aggregate
    prepared_df = prepared_df.groupby(['Provinsi', 'Kategori_Bencana'])['Jumlah_Kejadian'].sum().reset_index()
    prepared_df = prepared_df.sort_values('Jumlah_Kejadian', ascending=True)
    
    # Visualisasi
    if not prepared_df.empty:
        col_chart1, col_chart2 = st.columns([2, 1])
        
        with col_chart1:
            st.write("**📊 Kejadian Bencana per Provinsi**")
            # Area chart dengan gradien untuk visualisasi yang lebih smooth
            sorted_df = prepared_df.sort_values('Jumlah_Kejadian', ascending=True).reset_index(drop=True)
            sorted_df['rank'] = range(len(sorted_df))
            
            area_chart = alt.Chart(sorted_df).mark_area(
                line={'color': '#1f77b4'},
                color=alt.Gradient(
                    gradient='linear',
                    stops=[alt.GradientStop(color='lightblue', offset=0),
                           alt.GradientStop(color='darkblue', offset=1)],
                    x1=1, x2=1, y1=1, y2=0
                )
            ).encode(
                x=alt.X('rank:Q', title='Provinsi (Urutan)', axis=alt.Axis(labels=False)),
                y=alt.Y('Jumlah_Kejadian:Q', title='Jumlah Kejadian'),
                tooltip=['Provinsi', 'Kategori_Bencana', 'Jumlah_Kejadian']
            ).interactive()
            
            st.altair_chart(area_chart, use_container_width=True)
        
        with col_chart2:
            st.write("**📈 Statistik**")
            st.metric("Total Provinsi", len(prepared_df['Provinsi'].unique()))
            st.metric("Total Kejadian", int(prepared_df['Jumlah_Kejadian'].sum()))
            st.metric("Rata-rata per Provinsi", f"{prepared_df['Jumlah_Kejadian'].mean():.0f}")
        
        # Dampak Bencana per Provinsi - Stacked Bar Chart
        st.markdown("---")
        st.subheader("💔 Dampak Bencana per Provinsi")
        
        # Tombol untuk tampilkan semua provinsi di dampak chart
        col_dampak_btn, col_dampak_filter = st.columns([1, 3])
        with col_dampak_btn:
            if st.button("📍 Semua", help="Klik untuk melihat dampak semua provinsi", key='btn_dampak_all'):
                st.session_state.show_all_dampak = not st.session_state.get('show_all_dampak', False)
        
        with col_dampak_filter:
            if st.session_state.get('show_all_dampak', False):
                df_dampak_source = df_bencana
                st.info("✅ Menampilkan dampak semua provinsi")
            else:
                df_dampak_source = df_filtered
                st.caption(f"📊 Menampilkan {len(provinsi_selected)} provinsi yang dipilih")
        
        # Filter kategori dampak
        dampak_categories = st.multiselect(
            "🔍 Filter Kategori Dampak:",
            options=['Meninggal', 'Mengungsi', 'Total Rumah Rusak'],
            default=['Meninggal', 'Mengungsi', 'Total Rumah Rusak'],
            key='filter_dampak'
        )
        
        if dampak_categories:
            # Prepare dampak data dengan melt dari source yang sesuai
            df_dampak = df_dampak_source[['Provinsi'] + dampak_categories].copy()
            df_dampak_melted = pd.melt(df_dampak,
                                       id_vars=['Provinsi'],
                                       value_vars=dampak_categories,
                                       var_name='Kategori_Dampak',
                                       value_name='Jumlah')
            
            # Groupby dan aggregate
            df_dampak_melted = df_dampak_melted.groupby(['Provinsi', 'Kategori_Dampak'])['Jumlah'].sum().reset_index()
            
            # Total per provinsi untuk sorting
            total_per_prov = df_dampak_melted.groupby('Provinsi')['Jumlah'].sum().reset_index()
            total_per_prov = total_per_prov.sort_values('Jumlah', ascending=True)
            prov_order = total_per_prov['Provinsi'].tolist()
            
            # Stacked horizontal bar chart dengan height dinamis
            chart_height = max(400, len(prov_order) * 20)  # 20px per provinsi, minimum 400px
            dampak_chart = alt.Chart(df_dampak_melted).mark_bar().encode(
                y=alt.Y('Provinsi:N', sort=prov_order, title='Provinsi'),
                x=alt.X('sum(Jumlah):Q', title='Total Dampak'),
                color=alt.Color('Kategori_Dampak:N', title='Kategori Dampak',
                               scale=alt.Scale(scheme='set2')),
                tooltip=['Provinsi', 'Kategori_Dampak', 'Jumlah']
            ).interactive().properties(height=chart_height)
            
            st.altair_chart(dampak_chart, use_container_width=True)
            
            # Summary table
            st.write("**📊 Ringkasan Dampak**")
            summary_df = df_dampak_melted.groupby('Kategori_Dampak')['Jumlah'].sum().reset_index()
            summary_df.columns = ['Kategori Dampak', 'Total']
            
            col_s1, col_s2, col_s3 = st.columns(3)
            for idx, row in summary_df.iterrows():
                with [col_s1, col_s2, col_s3][idx]:
                    st.metric(row['Kategori Dampak'], f"{int(row['Total']):,}")
        
        
        # Download button
        csv = prepared_df.to_csv(index=False, encoding='utf-8-sig')
        st.download_button(
            label="📥 Download Data Kejadian sebagai CSV",
            data=csv,
            file_name="rekapitulasi_bencana.csv",
            mime="text/csv"
        )
    else:
        st.warning("⚠️ Tidak ada data dengan filter yang dipilih (Jumlah Kejadian > 0).")
else:
    st.info("ℹ️ Silakan pilih minimal satu provinsi.")

st.markdown("---")
# --- BAGIAN 5: PERINGKAT TAHUN BERDASARKAN KEHILANGAN TUTUPAN HUTAN ---
st.header("Peringkat Tahun Berdasarkan Kehilangan Tutupan Hutan")
df_loss_top_years = df_loss.sort_values('loss_ha', ascending=False).head(10)

loss_year_chart = alt.Chart(df_loss_top_years).mark_bar(color='#d90429').encode(
    x=alt.X('loss_ha:Q', title='Total Kehilangan (Ha)'),
    y=alt.Y('year:O', sort='-x', title='Tahun'),
    tooltip=['year', 'loss_ha']
)
st.altair_chart(loss_year_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini menampilkan 10 tahun dengan kehilangan tutupan hutan tertinggi dari tahun 2001-2024.")

# --- BAGIAN 6: DAMPAK BENCANA PER PROVINSI ---
st.header("Rincian Dampak Bencana per Provinsi")
provinsi_bencana_select = st.selectbox("Pilih Provinsi untuk Melihat Dampak Bencana:", df_bencana['Provinsi'].unique())

df_bencana_prov = df_bencana[df_bencana['Provinsi'] == provinsi_bencana_select]
dampak_data = df_bencana_prov[['Meninggal', 'Mengungsi', 'Total Rumah Rusak']].sum().reset_index()
dampak_data.columns = ['Jenis Dampak', 'Jumlah']

dampak_chart = alt.Chart(dampak_data).mark_bar(color='#fca311').encode(
    x=alt.X('Jumlah:Q', title='Jumlah'),
    y=alt.Y('Jenis Dampak:N', sort='-x', title='Dampak'),
    tooltip=['Jenis Dampak', 'Jumlah']
)
st.altair_chart(dampak_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini merinci jumlah korban jiwa, pengungsi, dan rumah rusak akibat bencana di provinsi yang dipilih.")

# --- BAGIAN 7: JENIS PELANGGARAN KEHUTANAN ---
st.header("Komposisi Jenis Pelanggaran di Provinsi Teratas")
top_10_provinsi_kasus = df_kasus.sort_values('JUMLAH', ascending=False).head(10)
kasus_melted = top_10_provinsi_kasus.melt(
    id_vars='PROVINSI',
    value_vars=['ILLEGAL_LOGGING', 'PERAMBAHAN_HUTAN', 'TUMBUHAN_SATWA_LIAR'],
    var_name='Jenis Pelanggaran',
    value_name='Jumlah Kasus'
)

stacked_bar_kasus = alt.Chart(kasus_melted).mark_bar().encode(
    x=alt.X('sum(Jumlah Kasus):Q', title='Total Kasus'),
    y=alt.Y('PROVINSI:N', sort=alt.EncodingSortField(field="sum(Jumlah Kasus)", op="sum", order='descending')),
    color=alt.Color('Jenis Pelanggaran:N', scale=alt.Scale(scheme='category10')),
    tooltip=['PROVINSI', 'Jenis Pelanggaran', 'Jumlah Kasus']
)
st.altair_chart(stacked_bar_kasus, use_container_width=True)
st.write("> **Catatan:** Grafik ini menunjukkan komposisi tiga jenis pelanggaran utama di 10 provinsi dengan jumlah kasus kehutanan tertinggi.")

# --- BAGIAN 10: PERBANDINGAN FUNGSI HUTAN DAN KEHILANGAN TUTUPAN ---
st.header("Total Kehilangan Tutupan Hutan vs Fungsi Hutan per Provinsi")
prov_compare_select = st.selectbox("Pilih Provinsi untuk Perbandingan:", df_def['PROVINSI'].unique(), key='prov_compare_selectbox')

# Data Fungsi Hutan
df_def_prov = df_def[df_def['PROVINSI'] == prov_compare_select].melt(
    id_vars='PROVINSI', value_vars=['HK', 'HL', 'HPT', 'HP', 'HPK', 'APL'],
    var_name='Kategori', value_name='Luas (Ha)'
)

# Data Kehilangan Tutupan Hutan
# Since df_loss does not have province data, we'll show the total loss for context.
# A better approach would be to have province data in the loss dataset.
total_loss_all_provinces = df_loss['loss_ha'].sum()
loss_df = pd.DataFrame([{'PROVINSI': prov_compare_select, 'Kategori': 'Total Kehilangan (Nasional)', 'Luas (Ha)': total_loss_all_provinces}])

# Gabungkan data
combined_df = pd.concat([df_def_prov, loss_df])

comparison_chart = alt.Chart(combined_df).mark_bar().encode(
    x=alt.X('Kategori:N', sort='-y', title='Kategori'),
    y=alt.Y('Luas (Ha):Q', title='Luas (Ha)'),
    color=alt.Color('Kategori:N', legend=None, scale=alt.Scale(scheme='spectral')),
    tooltip=['Kategori', 'Luas (Ha)']
)

st.altair_chart(comparison_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini membandingkan luas area berdasarkan fungsi hutan dengan total akumulasi kehilangan tutupan hutan di provinsi terpilih. Ini membantu melihat skala kehilangan hutan relatif terhadap luas hutan yang ada.")

st.markdown("Analisis ini menunjukkan bahwa wilayah dengan tingkat deforestasi tinggi atau aktivitas ilegal seringkali memiliki kerentanan terhadap bencana hidrometeorologi seperti banjir dan cuaca ekstrem.")
